name: CI Pipeline              # Workflow name (shows in GitHub UI)

on: [push, pull_request]      # When to run this workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Buliding"
      - run: echo "Building..."
  
  test:
    needs: build          # Wait for build to complete
    runs-on: ubuntu-latest
    steps:
      - run: echo("testing")
      - run: echo "Testing..."
  
  deploy:
    needs: [build, test]  # Wait for both build and test
    runs-on: ubuntu-latest
    steps:
      - run: echo "application"
      - run: echo "Deploying..."
  